export const HOME_ROUTE = 'HOME_KEY'

export const CUSTOMER_ROUTE = {
  INDEX: 'CUSTOMER_INDEX_KEY',
  CREATE: 'CUSTOMER_CREATE_KEY',
  UPDATE: 'CUSTOMER_UPDATE_KEY',
}

export const SERVICE_ROUTE = {
  INDEX: 'SERVICE_INDEX_KEY',
  CREATE: 'SERVICE_CREATE_KEY',
  UPDATE: 'SERVICE_UPDATE_KEY',
}
